version: "3"
services:
  dog-image-widget:
    image: dog-image-widget
    build:
      dockerfile: Dockerfile
      context: ./dog-image-widget
    container_name: dog-image-widget
    ports:
      - "3000:3000"
  dog-api:
    image: dog-api
    build:
      dockerfile: Dockerfile
      context: ./dog-api
    container_name: dog-api
    env_file: ./dog-api/.env
    environment:
      - PORT=3001
    ports:
      - "3001:3001"