version: "3"
services:
  dog-api:
    image: dog-api
    build:
      dockerfile: Dockerfile
      context: .
    container_name: dog-api
    env_file: .env
    environment:
      - PORT=3001
    ports:
      - "3001:3001"